### ISSUE TITLE
Add Cargo.lock to the repository (if there exist one)

### ISSUE THREAD

**Issue by mzji** [nabijaczleweli/cargo-update#10]
From the [Cargo reference](http://doc.crates.io/guide.html#cargotoml-vs-cargolock), for programs, Cargo.lock should be in the repository.

**Comment by nabijaczleweli** [comment]
But this is a library

**Comment by mzji** [comment]
Wait, there is a `[[bin]]` section in the Cargo.toml, so it should be a binary... right?

**Comment by nabijaczleweli** [comment]
There's a `[[bin]]` exactly because it's a library.

**Comment by nabijaczleweli** [comment]
Re: edit: that's because `cargo-tree` isn't a library

**Comment by mzji** [comment]
[cargo-edit](https://github.com/killercup/cargo-edit) is both a library and a binary, it contains a [Cargo.lock](https://github.com/killercup/cargo-edit/blob/master/Cargo.lock).

**Comment by nabijaczleweli** [comment]
Maybe killercup views it primarily as an exec, secondarily as a library, v0v.
This is a library first, an exec second (think of the exec like an example, which it basically is (and should be)).

**Comment by mzji** [comment]
Ah, OK, so maybe Cargo.lock should be added into the .gitignore , just like [Clippy](https://github.com/Manishearth/rust-clippy/blob/master/.gitignore)

**Comment by nabijaczleweli** [comment]
It is in `.gitignore` :v

**Comment by mzji** [comment]
Ah got it. Thanks for the explain!

**Comment by nabijaczleweli** [comment]
I like to use an inverted `.gitignore` - everything is ignored except the files specified with `!` before them
