### ISSUE TITLE
Doesn't respect system proxy

### ISSUE THREAD

**Issue by ThinkChaos** [nabijaczleweli/cargo-update#106]
At work I need to use the office proxy otherwise I can't connect to the internet over HTTP(S).
cargo-update doesn't detect the system proxy so it fails when trying to update the registry.

Could you add support for using system configured proxies?
Usually proxies are configured through `HTTP_PROXY` and `HTTPS_PROXY` environment variables.
For cargo specifically, it's `http.proxy` and `https.proxy` in `~/.cargo/config`.

**Comment by nabijaczleweli** [comment]
I'm currently away, but I'll see about stealing Cargo's behaviour when I get back on Monday. Thanks for the report!

**Comment by nabijaczleweli** [comment]
Please check if the [current `master`](https://github.com/nabijaczleweli/cargo-update/commit/a2229dd02d9a5a43de34b97201cb31a948ebd028) works for you?

**Comment by nabijaczleweli** [comment]
Released in [`v1.8.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.8.0), but it'd be nice to know if the behaviour is as expected on your system, too

**Comment by ThinkChaos** [comment]
Sorry I forgot to respond the first time.

It works great on my system!

**Comment by nabijaczleweli** [comment]
Kickass!
