### ISSUE TITLE
As of 1.8 this no longer builds with rustc 1.33

### ISSUE THREAD

**Issue by Lokathor** [nabijaczleweli/cargo-update#108]
Seems that the `json` 0.12 dependency doesn't work with rustc 1.33

<https://travis-ci.org/Lokathor/fermium/jobs/583458211>

I'm not sure if this is considered a big problem or not. My CI broke from it but I can just not use this in CI I guess.

**Comment by nabijaczleweli** [comment]
I released [`v1.8.1`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.8.1), downgrading `json` to 0.11 as it was before for now, and verified locally that it builds with 1.33.0, can you run your CI again as final test?

**Comment by Lokathor** [comment]
Seems to work, I think you've solve it, <https://travis-ci.org/Lokathor/fermium/jobs/583701766#L212>

**Comment by nabijaczleweli** [comment]
Kickass! Thanks for the report!
