### ISSUE TITLE
--version only prints the name of the crate

### ISSUE THREAD

**Issue by tuxiqae** [nabijaczleweli/cargo-update#111]
When I run version 1.8.4 with the flags "--version" or "-V", cargo-update should output the version of the binary (i.e. "cargo-update 1.8.4") but unfortunately it only outputs the name of the crate "cargo-install-update"
I honestly don't know what causes it as the !crate_version() macro is supposed to get it's value from the Cargo.toml file which is set correctly.
I also tried looking at other crates such as ripgrep and it seems like it was [implemented the same way](https://github.com/BurntSushi/ripgrep/blob/master/src/app.rs#L69) - both in the Cargo.toml and in clap.

Thanks

**Comment by tuxiqae** [comment]
Tested on Arch Linux, using version 1.8.4 both compiled from sources or updated using cargo-update

**Comment by nabijaczleweli** [comment]
I uh, can't reproduce this?

```
p:\Rust\cargo-update>cargo install-update -V
cargo-install-update 1.8.4

p:\Rust\cargo-update>which cargo-install-update
/d/Users/nabijaczleweli/.cargo/bin/cargo-install-update
```

Is your Cargo up-to-date?

**Comment by nabijaczleweli** [comment]
Actually, I just realised, if you run `cargo-install-update -V` you do, in fact, only get the binary name. The proper invocation is `cargo install-update -V` (note the space)

**Comment by tuxiqae** [comment]
Oh darn, once again you are right.
I still believe it should work for both :P

**Comment by nabijaczleweli** [comment]
Renamed the root name to `cargo` to diffuse any future confusion :Р

**Comment by tuxiqae** [comment]
Doesn't look like it'll fix the issue.
Don't you think that running the binary should output the version number?

**Comment by nabijaczleweli** [comment]
I do think that invoking the binary as `cargo-install-update{,-config}` should output the version number thereof, but I don't think getting `cargo`'s version is in the scope of this document.

**Comment by tuxiqae** [comment]
I completely agree with you about the first part.
I just think that when checking the version of `cargo-install-update{,-config}` you should see the version of cargo-update and not of cargo itself

**Comment by nabijaczleweli** [comment]
well yes, you do that by invoking them as their correct executables via `cargo install-update [OPTS]` (or, if you really insist, `cargo-install-update install-update [OPTS]`). The latter invocation being allowed at all is just a leaky implementation detail, quite frankly.
