### ISSUE TITLE
List flag (-l) should list all packages by default

### ISSUE THREAD

**Issue by Tranzystorek** [nabijaczleweli/cargo-update#114]
When `--list` is specified without `--all`, cargo-update says: "Need at least one PACKAGE without --all".

From a user standpoint, it feels like listing commands should be supported on their own by default, without explicitly specifying crates to list.

**Comment by nabijaczleweli** [comment]
Can you check if the commit above behaves as expected?

**Comment by Tranzystorek** [comment]
I can confirm it works as expected 😄

**Comment by nabijaczleweli** [comment]
Released in [`v2.1.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v2.1.0).
