### ISSUE TITLE
Duped package entries in `.crates.toml`

### ISSUE THREAD

**Issue by liigo** [nabijaczleweli/cargo-update#12]
with argment `-a` or `-al`:
```
C:\WINDOWS\system32>cargo install-update -a
    Updating registry `https://github.com/rust-lang/crates.io-index`

Package       Installed  Latest   Needs update
rustfmt       v0.4.1     v0.6.2   Yes
rustfmt       v0.6.2     v0.6.2   No
cargo-edit    v0.1.2     v0.1.3   Yes
cargo-edit    v0.1.3     v0.1.3   No
```

- There are two `rustfmt` here, but I think they should have to be `rustfmt.exe` and `cargo-fmt.exe`.
- There are two `cargo-edit` here, but I think they should have to be `cargo-add.exe` and `cargo-list.exe`.

After all packages up to date, no duplicate package names are printed.

**Comment by nabijaczleweli** [comment]
Your `.cargo.toml`?

**Comment by nabijaczleweli** [comment]
> There are two rustfmt here, but I think they should have to be rustfmt.exe and cargo-fmt.exe.

Nah, we don't check the execs, just package descriptors.

> There are two cargo-edit here, but I think they should have to be cargo-add.exe and cargo-list.exe.

Same, really.

**Comment by nabijaczleweli** [comment]
It is possible to install the same package twice and have it linger in package descriptors, but it's not easy to *just* fuck it up. If after updating it works that means your `.crates.toml` somehow *had duplicate package names originally*.

**Comment by nabijaczleweli** [comment]
Closing since *using* cargo-update fixed it.
