### ISSUE TITLE
Suggestion: Summarize at the end which packages were updated.

### ISSUE THREAD

**Issue by ctsrc** [nabijaczleweli/cargo-update#120]
When updating a lot of packages, the scroll-back is long and since it begins updating right away there is no time to read which packages are going to be updated.

At the end, cargo-install-update says how many packages were updated but I think it would be useful if it would also state which packages were updated.

**Comment by nabijaczleweli** [comment]
Does the referenced commit work for you?

**Comment by ctsrc** [comment]
Yes, that's perfect. Thank you! And very quick response also so thanks for that. So fast in fact that it looks like you went back in time ;P

**Comment by nabijaczleweli** [comment]
Clocks are hard, brains are harder, you know how it be.

Released in [`v2.5.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v2.5.0).
