### ISSUE TITLE
Update cargo-update first

### ISSUE THREAD

**Issue by ThinkChaos** [nabijaczleweli/cargo-update#122]
I think it would be a good idea to always update cargo-update first when running `cargo install-update --all`.

**Comment by nabijaczleweli** [comment]
Hmm, any reasoning so as to why? It's not like we reexec from disk after updating, so I can't really see any obvious benefit to it?

**Comment by ThinkChaos** [comment]
Yeah sorry that wasn't quite clear. With the goal of starting the new version afterwards.
It's just a thing that would be nice to have.

**Comment by nabijaczleweli** [comment]
I've thought about it and I don't think the added code complexity (especially for Windows self-updates/alt reexec path entirely) is worth the benefits, especially nowadays when this crate is mostly in maintenance mode, but thank you for the suggestion.
