### ISSUE TITLE
Installing on macOS

### ISSUE THREAD

**Issue by jasikpark** [nabijaczleweli/cargo-update#123]
To install on macOS, first it was failing because I only had OpenSSL 9.8.0, and once I installed OpenSSL via brew, it worked fine.

```shell
calebjasik@Calebs-MacBook-Pro ~ %   export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
calebjasik@Calebs-MacBook-Pro ~ % cargo install cargo-update
```

I successfully installed it and ran it, just wanted to provide a success story for macOS. It wasn't entirely clear from the README why it wasn't working other than OpenSSL being the culprit

**Comment by nabijaczleweli** [comment]
Thanks! I've [added your steps to the README](https://github.com/nabijaczleweli/cargo-update/commit/2e81f5c35d35e9359053b3e1cea183abd5ea60de)
