### ISSUE TITLE
Necessary packages removed from Ubuntu repositories

### ISSUE THREAD

**Issue by denningsrogue** [nabijaczleweli/cargo-update#125]
After Ubuntu 18.4, the openssl-devel and libssl1.0.0 packages have been removed from the Ubuntu repositories.

**Comment by nabijaczleweli** [comment]
How about `libssl-dev`?

**Comment by denningsrogue** [comment]
Hi there

Libel-dev is in the repository but it uses a later version of libssl.

**Comment by denningsrogue** [comment]
Sorry about the auto correct:   libssl-dev is in the repository.

**Comment by nabijaczleweli** [comment]
Going by https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libssl-dev&searchon=names all repositories package 1.0.x or 1.1.x, so unless you have a concrete build error then I'm not sure how to help you.

Also note: both macOS (openssl 1.1 via brew, #123) and my sid (libssl-dev @ 1.1.1d-2) build, so I'm not sure why it'd fail in the first place?

**Comment by nabijaczleweli** [comment]
I ran some tests – a clean default and minimal chroot of bionic (current LTS) and eoan (latest); both worked.

My debootstrap needed a `sudo ln -s gutsy /usr/share/debootstrap/scripts/eoan`, but otherwise, substitute `bionic` for `eoan` everywhere and it'll work.

Default:
```bash
sudo debootstrap bionic bionic
sudo mount --bind /proc bionic/proc
sudo chroot bionic

apt install wget build-essential libssl-dev pkg-config
wget -O- https://sh.rustup.rs | sh
```

Minimal:
```bash
sudo debootstrap --variant=minbase bionic bionic
sudo mount --bind /proc bionic/proc
sudo chroot bionic

apt install --no-install-{suggest,recommend}s wget build-essential libssl-dev pkg-config ca-certificates
wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init && chmod +x rustup-init && ./rustup-init --profile minimal
```

Then the following works with no problems:
```
cargo install cargo-update
cargo install-update -a
```

My packaging woes were answered by these two paragraphs from the `openssl-dev` error:
> Make sure you also have the development packages of openssl installed.
> For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
>
> It looks like you're compiling on Linux and also targeting Linux. Currently this
> requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
> could not be found. If you have OpenSSL installed you can likely fix this by
> installing `pkg-config`.

Closing as norepro.
