### ISSUE TITLE
Cargo has built in install+upgrade functionality 

### ISSUE THREAD

**Issue by hayalci** [nabijaczleweli/cargo-update#130]
`cargo install` command in stable cargo now supports install+upgrade functionality

e.g. https://doc.rust-lang.org/stable/cargo/commands/cargo-install.html
>EXAMPLES
>Install or upgrade a package from crates.io:
>$ cargo install ripgrep

This was covered in rust-lang/cargo#6797 and PR rust-lang/cargo#7560

It doesn't cover the 'upgrade all packages' use case, but it's still a good idea to mention this development in the repository README.md.

**Comment by nabijaczleweli** [comment]
Thanks for the heads-up!

From a cursory glance and a short test, this doesn't seem much different from cargo's behaviour heretofor, except for adding another file with god-knows-what; at least it doesn't look like we have to parse it.

**Comment by nabijaczleweli** [comment]
Released in [`v4.0.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v4.0.0).
