### ISSUE TITLE
MSVC does actually require an explicit manifest, currently ignored

### ISSUE THREAD

**Issue by liigo** [nabijaczleweli/cargo-update#14]
```
cannot open input file 'cargo-install-update-manifest.lib'
```

that .lib was not created by build.rs

**Comment by nabijaczleweli** [comment]
Argh, I think I know why, can you try again with this patch applied

```diff
diff --git a/src/main.rs b/src/main.rs
index ede6561..76a5455 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,6 +1,7 @@
 // This is so cargo actually considers linking to the fucking manifest,
 // since the build scripts' documentation can do the digital equivalent of fucking off
 #[cfg(target_os="windows")]
+#[cfg(target_env="gnu")]
 #[link(name="cargo-install-update-manifest", kind="static")]
 extern "C" {}
```

**Comment by liigo** [comment]
that means, no manifest is embedded (for msvc ABI), and can't be run without Administrator privilege

**Comment by nabijaczleweli** [comment]
Okay, so I have to work around that, too, now

**Comment by nabijaczleweli** [comment]
Can you try the `fix/14-manifest-embed-msvc` branch? It should build&link in an MSVC-compatible way.
If you get object type errors try replacing `"--output-format=coff"` with `"--output-format=res"`, please.

**Comment by liigo** [comment]
I will

**Comment by mzji** [comment]
If the content of the manifest file won't be changed, then I think we don't need to compile it, we  could just write the file with the name "cargo-install-update.exe.manifest" to the `$HOME\.cargo\bin\` directory.

The advantage of this method is, we do not need to worry about the compiler/triples, the writing code will work on any Windows environment, since it only uses the std library.

**Comment by nabijaczleweli** [comment]
No

**Comment by liigo** [comment]
@nabijaczleweli 
Branch `fix/14-manifest-embed-msvc` Build failed.
I don't think there is a `windres.exe` in MSVC toolchain.

**Comment by nabijaczleweli** [comment]
Updated the branch to use `RC.EXE`, try again, please?

**Comment by liigo** [comment]
@nabijaczleweli 
After some changes to `cargo-install-update-manifest.rc`, build success.
But it doesn't work, the manifest resource was not linked into `.exe`.

Changes to `cargo-install-update-manifest.rc`:
```
@@ -1,2 +1,2 @@
-#include "winuser.h"
-1 RT_MANIFEST cargo-install-update.exe.manifest
+#define RT_MANIFEST 24
+1 RT_MANIFEST "cargo-install-update.exe.manifest"
```

----

If you don't mind, I'd like to have a try to submit a new pr.

**Comment by nabijaczleweli** [comment]
Have at it
