### ISSUE TITLE
Failed to update index repository when using WSL (v1 or v2)

### ISSUE THREAD

**Issue by iliekturtles** [nabijaczleweli/cargo-update#148]
When attempting to use `cargo-update` in a WSL bash shell (WSL 1 or WSL 2) the update registry step fails with the error message shown below.

```
$ cargo install-update -i ripgrep
    Updating registry 'https://github.com/rust-lang/crates.io-index'
Failed to update index repository: failed to resolve address for github.com: Temporary failure in name resolution.
```

Using `cargo install` in the same shell works.

```
$ cargo install ripgrep
    Updating crates.io index
  Downloaded ripgrep v12.1.1
  Downloaded 1 crate (256.5 KB) in 0.80s
  Installing ripgrep v12.1.1
  ...
```

Using `cargo-update` in a git bash (MINGW64) shell also works.

```
$ cargo install-update -i ripgrep
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package  Installed  Latest   Needs update
ripgrep  v12.1.1    v12.1.1  No

No packages need updating.
Overall updated 0 packages.
```

What additional information would be useful to diagnose the issue?

**Comment by nabijaczleweli** [comment]
What's your `/etc/resolv.conf` and `ldd` on `cargo` and `cargo-install-update`? A bit of a shot in the dark, but if one somehow uses a different resolver/libgit2 from the other this might me what results.

**Comment by nabijaczleweli** [comment]
Weird! Indeed, I don't see any good reason for the resolver to be angry in one case but not the other.
Glad it works, either way!
