### ISSUE TITLE
cargo-update and yanked update

### ISSUE THREAD

**Issue by speace** [nabijaczleweli/cargo-update#149]
Hi, first of all thanks for this amazing tool.

Today I noticed a weird issue with cargo-update and yanked version of a tool.
I updated tarpaulin a few days ago, cargo-update installed the v0.17.0 version but it then got yanked.  
So now according to cargo-update I have tarpaulin v0.17.0 while the latest is v0.16.0 (but nothing is breaking).  

Should cargo-update be allowed to automatically downgrade ? Should it check that the installed version has been yanked and print some warning + have an option to downgrade ?

**Comment by nabijaczleweli** [comment]
Can you try with current `master` (at least d4befee3de26a6d0cbcaf3d87fb6acb79fc95dd6)?

**Comment by speace** [comment]
Sorry I've been busy for the last few days, I tried today and it worked perfectly. I'm now on the latest not yanked version of tarpaulin.

**Comment by nabijaczleweli** [comment]
Cool. Released in [v4.2.0](https://github.com/nabijaczleweli/cargo-update/releases/tag/v4.2.0) (hehe weed number), then.
