### ISSUE TITLE
Package updates are no longer detected

### ISSUE THREAD

**Issue by saghm** [nabijaczleweli/cargo-update#15]
I just noticed that a couple of my installed packages are shown as updated on crates.io, but the newer versions are not showing up with `cargo install-update`. For example:

```
% cargo search cargo-check
    Updating registry `https://github.com/rust-lang/crates.io-index`
cargo-check (0.2.2)     wrapper around cargo rustc -- -Zno-trans
...
```

```
% cargo install-update -a
    Updating registry `https://github.com/rust-lang/crates.io-index`

Package         Installed  Latest   Needs update
cargo-check     v0.2.1     v0.2.1   No
```

I'm currently running version 0.5.1, which looks like the latest.

EDIT: Forgot to mention, this is on an x86_64 linux machine

**Comment by nabijaczleweli** [comment]
I can't reproduce myself, but: what's the freshest directory in `$CARGO_HOME/registry/index` (do you have multiple)? If you have more than 1, look in `INDEX_DIR/ca/rg/cargo-check` in each one to see if the freshest index dir has the newest (i.e. with 0.2.2) package data.

This might be another Windooze-Linux difference, where Linux doesn't update the dir modification stamp when changing files inside it.

**Comment by saghm** [comment]
Yep, there were two indexes in the registry, and deleting the older one fixed it. Thanks!

**Comment by nabijaczleweli** [comment]
But I *check* for that! That should just... work. Why doesn't it? urgh

**Comment by dtolnay** [comment]
I am still seeing this with cargo-update 0.6.6 on linux. I have three directories in `$CARGO_HOME/registry/index` timestamped Jan 20, Jan 27, Feb 2. Removing the two oldest did not solve the problem but removing the youngest and oldest did. Any idea where these extra indexes come from?

**Comment by nabijaczleweli** [comment]
I don't, unfortunately, no. Probably worth taking up an issue over at https://github.com/rust-lang/cargo
