### ISSUE TITLE
Allow custom install command to overwrite default install behavior

### ISSUE THREAD

**Issue by SirWindfield** [nabijaczleweli/cargo-update#151]
It would be great if there was a way to specify a custom install command instead of `cargo-update` invoking `cargo install` in the background. Tools similar to [cargo-quickinstall](https://github.com/alsuren/cargo-quickinstall) would then be able to integrate with `cargo-update`. Instead of updating by compiling the binary itself on the local machine, the custom command could use used to invoke `cargo-quickinstall`, which downloads a pre-built binary in most cases :) Maybe a `-r,--run` argument?

I'd imagine something like this maybe: `cargo install-update -a -r 'cargo quickinstall {}'`. For each package to update, `cargo-update` could then simply replace all occurrences of  `{}` with the crate name.

 Thoughts?

**Comment by nabijaczleweli** [comment]
Try current `master` branch (at least 84ece88ac846faf020d69a0d1a79ffda5e95501e) — you should be able to set `-r`/`--install-cargo` to a wrapper and munge those arguments to whatever your heart desires.

**Comment by SirWindfield** [comment]
Awesome, thanks!

**Comment by nabijaczleweli** [comment]
Released in [`v5.1.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v5.1.0)
