### ISSUE TITLE
thread `main` panicked at `No FETCH_HEAD`

### ISSUE THREAD

**Issue by fmckeogh** [nabijaczleweli/cargo-update#153]
Apologies if this is a duplicate of #139  but I get the following panic when updating the `dog` package installed from `git`.

```
~ $ cargo install-update -ag
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package         Installed  Latest    Needs update
b3sum           v0.3.7     v0.3.7    No
...
websocat        v1.8.0     v1.8.0    No

No packages need updating.
thread 'main' panicked at 'No FETCH_HEAD in /Users/ferdiamckeogh/.cargo/git/db/dog-a6b49d2c6bfa9496: corrupted loose reference file: FETCH_HEAD; class=Reference (4)', /Users/ferdiamckeogh/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-update-6.0.0/src/ops/mod.rs:523:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've cleaned the `.cargo` directory several times but after a few updates I get the error again.

**Comment by nabijaczleweli** [comment]
What's the URL you're installing from?

**Comment by fmckeogh** [comment]
`cargo install --git https://github.com/ogham/dog`

I have several other crates installed from `git` and as far as I can tell `dog` is the only one causing issues. I also accept this isn't a very helpful bug report; I'm happy to close it and come back later if I can provide a minimal failing case.

**Comment by nabijaczleweli** [comment]
Hm, can't reproduce this. `cargo install dog --git https://github.com/ogham/dog`, then `cargo install-update -lag` just prints
```
nabijaczleweli@tarta:~/code/cargo-update$ ./target/debug/cargo-install-update install-update -lag
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package     Installed  Latest                               Needs update
cargo-deb   v1.27.0    v1.29.2                              Yes
checksums   v0.6.0     v0.7.1                               Yes
cargo-tree  v0.29.0    v0.29.0                              No
pijul       v0.12.2    v0.12.2 (v1.0.0-alpha.48 available)  No
termimage   v1.1.0     v1.1.0                               No
treesize    v0.5.0     v0.5.0                               No
xargo       v0.3.22    v0.3.22                              No

Package      Installed                                 Latest                                    Needs update
cargo-cache  5f9fc7c3a8c5d66132f3cb364fac38b26029642f  24dad56a5e59189a5796ba14001d23c190bb1ccd  Yes
dog          848697a9b89b73fc253607ff757f48341827a5bf  848697a9b89b73fc253607ff757f48341827a5ba  Yes
```
which appears correct.

Can you, maybe, tar up `~/.cargo/git/db/dog-*` and post it here, along with your `~/.cargo/.crates.toml` and `cargo --version` output?

**Comment by fmckeogh** [comment]
[dog-a6b49d2c6bfa9496.tar.gz](https://www.icloud.com/iclouddrive/04W7NLV6YYRLS3b3MVeDcokSQ#dog-a6b49d2c6bfa9496)

[~/.cargo/.crates.toml](https://gist.github.com/fmckeogh/f94e5562599da0478ce469f12ead05e1)

```
$ cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)
```

**Comment by nabijaczleweli** [comment]
Yeah, okay, this repo works for me and behaves like I'd expect under strace, so uhhh maybe you have a broken libgit2?

Or, since your `.crates.toml` doesn't appear to have `dog` in it, try appending
```toml
"dog 0.5.1 (git+https://github.com/ogham/dog#5f9fc7c3a8c5d66132f3cb364fac38b26029642f)" = ["dog"]
```
to it and see how that treats you, maybe?

**Comment by fmckeogh** [comment]
Ah sure, it's probably something wrong with my machine. I cleaned everything and reinstalled, appears to be fine again. Thank you for the help though!
