### ISSUE TITLE
Requires OpenSSL on Windows

### ISSUE THREAD

**Issue by Zymlex** [nabijaczleweli/cargo-update#169]
This problem: https://github.com/nabijaczleweli/cargo-update/commit/57babcbfb8ebbc6a77c011d60d51e1c28ffb0e8c

![image](https://user-images.githubusercontent.com/25817412/145702150-09350ae7-a781-486c-951d-75102b3cca11.png)

**Comment by nabijaczleweli** [comment]
uhoh, good point

**Comment by nabijaczleweli** [comment]
Can you try the current `master` branch (at least 2ac1649d87b8a0e68fc9075165da34cd96182bbf)?

**Comment by nabijaczleweli** [comment]
Verified independently, released in [`v8.1.1`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v8.1.1)
