### ISSUE TITLE
[Feature] add an option to install all crates while skipping already installed crates

### ISSUE THREAD

**Issue by MrNossiom** [nabijaczleweli/cargo-update#174]
Hi everyone, 

First, I find this tool really useful, so thanks to all of you.

I have a kind of automated `.dotfiles` repo to share configs between my machines,
and so I use this tool to keep a consistent list of all globally installed crates between these.
But this has limitations, and currently I don't see any way to check which crates are already installed.
I can't automate the process of installing these because I don't want to recompile everything with the `--all` flag nor install them manually.

I would love such a feature.  A flag like `--skip-installed` to trigger another filter mechanism. I don't if this is simple to implement, and I could make a PR for this, but I want to be sure you would accept this feature in this tool.

Thanks

**Comment by nabijaczleweli** [comment]
Would `cargo install --list | awk '/:/ {print $1}'` work as a "way to check which crates are already installed"?

**Comment by MrNossiom** [comment]
Hi,

This is not exactly the thing I'm searching for.

I want to install the crates that are not already compiled and up-to-date. For example, in my `.crates.toml` I have 3 dependencies ? But in my `bin` directory, only 2 of them are compiled and ready to use.

In my `.crates.toml`: `cargo-expand`, `git-leave` and `tokei`
But in my `bin` directory: `cargo-expand` and `git-leave`

With the actual options, I could either install `tokei` manually (which is not a possible solution 😄) or reinstall everything with `cargo install-update --all` (which takes a lot of time and resources if you have 12 deps or more)

**Comment by nabijaczleweli** [comment]
See, that's just an invalid configuration. I see what you're driving at, but `.crates.toml` is a *description*, not a dependency list or configuration. It is the ground truth. Whatever you do to your `~/.cargo/bin` is irrelevant.

That being said,
```
nabijaczleweli@tarta:~$ sed -n 'H;/]$/bend;d;:end s/.*//;x;s/\n//g;p'  .cargo/.crates.toml
[v1]
"cargo-bloat 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-cache 0.5.1 (git+https://github.com/matthiaskrgr/cargo-cache#5f9fc7c3a8c5d66132f3cb364fac38b26029642f)" = ["cargo-cache"]
"cargo-deb 1.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deb"]
"cargo-tree 0.29.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 4.1.0 (path+file:///home/nabijaczleweli/code/cargo-update)" = [    "cargo-install-update",    "cargo-install-update-config",]
"checksums 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["checksums"]
"dog 0.5.1 (git+https://github.com/ogham/dog#5f9fc7c3a8c5d66132f3cb364fac38b26029642f)" = ["dog"]
"feembox 0.1.1 (path+file:///home/nabijaczleweli/code/feembox)" = ["feembox"]
"https 1.12.4 (path+file:///home/nabijaczleweli/code/http)" = [    "http",    "httplz",]
"pijul 0.12.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["pijul"]
"pixelmatch 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["pixelmatch"]
"termimage 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"treesize 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["treesize"]
```
gets you a one-entry-per-line `.crates.toml`, so
```
nabijaczleweli@tarta:~$ sed -n 'H;/]$/bend;d;:end s/.*//;x;s/\n//g;p'  .cargo/.crates.toml   | awk -F= '/\((registry|git)\+/ {sub(/"/, "", $1); sub(/ .*/, "", $1); gsub(/[ "\[\]]/, "", $2); sub(/,$/, "", $2); split($2, b, ","); for(i = 1; i <= length(b); ++i) print "[ -x ~/.cargo/bin/" b[i] " ] || echo " $1 }'  | sh | uniq
dog
```
gives you all the crates which have at least one missing binary, so stuff that into `cargo install-update $(sed | ... )` and you're off. Stuff into a variable first and -z if the error you get if all crates have all the binaries bothers you, or just do
```
sed -n 'H;/]$/bend;d;:end s/.*//;x;s/\n//g;p'  .cargo/.crates.toml   | awk -F= '/\((registry|git)\+/ {sub(/"/, "", $1); sub(/ .*/, "", $1); gsub(/[ "\[\]]/, "", $2); sub(/,$/, "", $2); split($2, b, ","); for(i = 1; i <= length(b); ++i) print "[ -x ~/.cargo/bin/" b[i] " ] || cargo install-update " $1 }'  | sh
```
instead maybe.

Is that satisfying for your needs?

**Comment by MrNossiom** [comment]
Hi,
I had to test it on my computer, but I'm finally back.

But I have a problem with the `sed` command, when I execute it gives me this error: 
`sed: 1: "H;/]$/bend;d;:end s/.*/ ...": undefined label 'end;d;:end s/.*//;x;s/\n//g;p'`.

And if I remove the part of the expression causing the error, so executing this expression
`H;/]$/bend;d;:end s/.*//;x;s/\n//g;p`, I get as many blank lines as my file has new lines.

Thanks for your time and attention.

**Comment by nabijaczleweli** [comment]
Are you on a weird `sed`? This works, for me, with both busybox and GNU sed on bullseye. That being said, `sed -n 'H;/]$/bend d;:end s/.*//;x;s/\n//g;p' .cargo/.crates.toml` (i.e. the branch target delimited with a space instead of semicolon) might work better?

**Comment by MrNossiom** [comment]
I don't know what was supposed to do `sed`, but I tried with only `awk` and it works.

I ended up with this script that works like paradise:
```bash
# If the .crates.toml file doesn't exist, exit with code 1
if [ ! -s ".cargo/.crates.toml" ]; then
	exit 1
fi

# Install all the missing binaries
cargo install-update -f $(
	# Dynamically create a script with awk to check if the corresponding binary exists
	awk -F= '/\((registry|git)\+/ {
		sub(/"/, "", $1);
		sub(/ .*/, "", $1);
		gsub(/[ "\[\]]/, "", $2);
		sub(/,$/, "", $2); split($2, b, ",");
		for(i = 1; i <= length(b); ++i) print "[ -x ~/.cargo/bin/" b[i] " ] || echo " $1
	}' .cargo/.crates.toml |

	# Execute the script and filter duplicates if any
	sh | uniq
)
```

Thank you

**Comment by MrNossiom** [comment]
Hey,
This is now the final script that I tweaked a little : 
https://github.com/MrNossiom/dotfiles/blob/0179f79d5ac2e000f1a853209584aa8d1eee6247/scripts/rust_deps_update.sh
It is going perfectly well with config.
Thanks again
