### ISSUE TITLE
[Feature] List packages which need updating only

### ISSUE THREAD

**Issue by yermulnik** [nabijaczleweli/cargo-update#175]
Is there an option to list only packages which need updating, otherwise produce no output?
My use case: I'd like to run something like `cargo install-update -al` via crontab to be notified when there are any updates pending w/o actually updating packages and w/o list packages which don't need updating. Thanks.

**Comment by nabijaczleweli** [comment]
```sh
$ cargo install-update -lag | awk '$NF == "Yes"'
cargo-deb    v1.35.0    v1.37.0                          Yes
checksums    v0.6.0     v0.9.1                           Yes
termimage    v1.1.0     v1.2.0                           Yes
xargo        v0.3.24    v0.3.25                          Yes
cargo-cache  5f9fc7c3a8c5d66132f3cb364fac38b26029642f  4ac2c2029ca3d30e2635f01138614462230e386a  Yes
dog          5f9fc7c3a8c5d66132f3cb364fac38b26029642f  721440b12ef01a812abe5dc6ced69af6e221fad5  Yes
```

**Comment by yermulnik** [comment]
Thanks. This is exactly the workaround I use at the moment, whereas I was asking of whether there's a builtin `cargo-update` option to achieve the same.

**Comment by nabijaczleweli** [comment]
There is, it's `-lag | awk '$NF == "Yes"'`. You have a stability guarantee for this.

**Comment by yermulnik** [comment]
I see your point, though I was asking of something like `brew outdated`, which is self-contained builtin as opposite to a need to use external dependency like `awk`.
Thanks for the input.

**Comment by yermulnik** [comment]
For those who find themselves seeking for automation around this, here's my `crontab` schedule for `cargo-update`:
```shell
25 03 * * * DATA=$(cargo install-update -alg | awk '{if ($1 == "Package" && !header) header = $0; if ($NF == "Yes") packages[$1] = $0} END {if (length(packages) > 0) {print header; for (package in packages) print packages[package]; print "\nTo upgrade run:\ncargo install-update -a"}}'); [ "${DATA}" ] && echo "${DATA}" | mail -s "cargo packages need updating" PUT_YOUR_EMAIL_HERE
```

**Comment by MostHated** [comment]
Here is a quick powershell update check as well.

```powershell
function check_cargo_update() {
    $updateData = cargo install-update -alg
    $needUpdate = [System.Collections.ArrayList]::new()
    $updateData | % { if (($results = -split $_)[3] -eq 'Yes') { [void]$needUpdate.Add($results[0]) } }
    echo "$($needUpdate.count) cargo updates are available"
    echo "$needUpdate"
}
```

<details>
<summary>Output</summary>

![](https://img.instance.id/lRcP8J8gvAf3/direct)

</details>
