### ISSUE TITLE
minor build issue with upstream openssl

### ISSUE THREAD

**Issue by jstelzer** [nabijaczleweli/cargo-update#177]
I have an m1 macbook.

I was running topgrade to update 'all the things' to latest.

I got a weird error upgrading cargo-update and ran it manually. It kept complaining about x86_64 libs trying to be ussed on aarch64 which seemed weird. IIRC this was building openssl's crate.

My work around is this:
```
export OPENSSL_DIR=/opt/homebrew/Cellar/openssl@1.1/1.1.1n
cargo install  --target aarch64-apple-darwin cargo-update
```

The above worked. Obviously this is the latest openssl from homebrew i'm using. Topgrade ran after this fine. This is mostly to help anyone else who runs into this.

**Comment by nabijaczleweli** [comment]
If your default target is already `aarch64-apple-darwin` (which I'm assuming it must be, otherwise you're running everything via rosetta) and you don't have an amd64 openssl installed, then I think you're best off opening an issue on https://github.com/sfackler/rust-openssl.
