### ISSUE TITLE
Enable to choose whether to really update a package or not

### ISSUE THREAD

**Issue by kyoheiu** [nabijaczleweli/cargo-update#179]
Hi, great app!
I think this would be easier to use to add option to choose whether to really update a package or not, like `pacman` does.

example:
![2022-05-05_05-25](https://user-images.githubusercontent.com/61998590/166820038-24e66255-d3b4-4725-b040-0125d1e10d37.png)

If there are many packages to update, you know it takes so much time to build in rust... so sometimes it's better not to update some packages and keep them as is.

Maybe adding a question to enter the number to exclude from update is enough. How do you think?

**Comment by nabijaczleweli** [comment]
Pass `-l`?

**Comment by kyoheiu** [comment]
That's I wanted. Thanks.

Have you considered to make `-l` option as default? Like, `cargo-instal update` shows list and enalbe to choose which packages to update, as fool-proof (yes I'm fool).

**Comment by nabijaczleweli** [comment]
Too late now, it'd be an atrocious API break; you can always ^C.

**Comment by kyoheiu** [comment]
Ok, understood. Thank you.
