### ISSUE TITLE
Maybe clarify 'downdate' a bit?

### ISSUE THREAD

**Issue by HenkPoley** [nabijaczleweli/cargo-update#183]
"Downdate packages to match newest unyanked registry version." feels a bit.. technical.. Like, if you know what it means, you don't need to read the documentation.

I suppose it is when the current package version is no longer available, and there is no newer version, it will try to downgrade.

**Comment by nabijaczleweli** [comment]
And your proposed wording is?

By default we only allow updates, `-d` allows downdates. By default, therefore, a crate needs to be installed if the latest unyanked registry version is greater than the current one, with `-d` if it's different.
If you subtract the trivial default you're left with "Allow downdates to match the latest unyanked version in the registry", which is the same as the manual and usage string.

**Comment by HenkPoley** [comment]
It is probably "fine". It is just that registry, unyanked and downdate are jargon.

So people who are not into writing package management, and in particular rust cargo packages, will not know these words.

**Comment by HenkPoley** [comment]
If I correctly understand what it does (and I am not sure), I would write/prepend it like this:

Allow downgrades if the current or a more recent version is no longer available online. Specifically, allow downdates to match the latest unyanked version in the registry.
