### ISSUE TITLE
Does not compile on aarch64 (android+termux) 

### ISSUE THREAD

**Issue by AlexCzar** [nabijaczleweli/cargo-update#184]
Tried to install using official method `cargo install cargo-update` on android using termux.
Error log is attached. 
[error.txt](https://github.com/nabijaczleweli/cargo-update/files/9399718/error.txt)

**Comment by nabijaczleweli** [comment]
wowee, exciting time to be a phone user!

> error: failed to run custom build command for `libssh2-sys v0.2.23`

Forwarded to https://github.com/alexcrichton/ssh2-rs/issues/256

**Comment by AlexCzar** [comment]
> wowee, exciting time to be a phone user!
Yep :) It's quite frustrating to have a computing powerhouse in one's pocket and only use it for messaging and reading :D

## Solution
```bash
; pkg install binutils-is-llvm
; AR=llvm-ar cargo install cargo-update
```
