### ISSUE TITLE
Feature request: Self update using `cargo-binstall`?

### ISSUE THREAD

**Issue by NobodyXu** [nabijaczleweli/cargo-update#195]
I just upgraded `cargo-update` to v0.9.0 and I was surprised to see `cargo-install` being invoked to install new versions of `cargo-update`.

It would be great if `cargo-update` could also provide binaries which `cargo-binstall` can use to download and upgrade without building it locally, which is time and resource consuming.

[Supporting `cargo-binstall`](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md) is not very hard.
It requires:
 - Pre-built binaries to be put into release artifacts
 - Uses static linking for best compatibility

The static linking part is a bit tricky though.

**Comment by nabijaczleweli** [comment]
I don't provide binary distributions of c-u and don't intend to. Installing non-system somehow-configured uncheckable and unverifiable versions of libssh(!) and openssl(!) and whatever else is best described as "lmao". The *only* supported distribution is tarball-at-tag, which is mirrored on crates.io.
