### ISSUE TITLE
Don't show list of installed packages on update by default

### ISSUE THREAD

**Issue by exploide** [nabijaczleweli/cargo-update#196]
I like to run `cargo install-update -a` in sequence with several other package managers to update basically everything I have installed. But `cargo install-update -a` outputs some more information than necessary. Especially the table of all installed packages, which seems to be the output of `-l`.

I would like to request not showing this list on installed packages by default when applying updates. Most of them have no update available and just clutter the output. I think that's too much.

But of course, some people might like this overview. So maybe it would be great to allow the combination of `-l` and `-a` to bring back the current behavior.

**Comment by nabijaczleweli** [comment]
`| grep -v No$`

**Comment by exploide** [comment]
Sure, manually fiddling with the output in a post processing step is possible. But I thought this would be a sensible default, because once the table grew large in size, it is just annoying.

But if you like to stay with the current behavior, I'll see what I can do on my side.
