### ISSUE TITLE
I would like a CHANGELOG to understand the news

### ISSUE THREAD

**Issue by frederikhors** [nabijaczleweli/cargo-update#198]
Why the Releases page is behind?

![image](https://user-images.githubusercontent.com/41120635/191714706-8a31400b-d1f4-4523-9139-92e3304c42d9.png)

Thanks for your work.

**Comment by nabijaczleweli** [comment]
Ask GitHub why they broke it; rollup changelog has always been and will always be in the tags – https://github.com/nabijaczleweli/cargo-update/tags.

**Comment by frederikhors** [comment]
I don't understand why you closed it. And why the `question` label.

Github is working good. Something in your repo changed.

Please re-open so we can understand and fix.

Thanks.

**Comment by nabijaczleweli** [comment]
I could frankly hardly care less about GitHub UI. Rollup changelog is in the tags, verbose changelog is in the commit messages.

If you want a better web-page for it then mirror it to sourcehut or whatever (0 post-processing):
![image](https://user-images.githubusercontent.com/6709544/191719649-6332b1a4-ae94-43aa-9a35-67b7e8bdc10c.png)
Or `git tag --sort=taggerdate -ln999`. Or tell github to unfuck it. Or
