### ISSUE TITLE
Options to update dependencies to "at least X days old"

### ISSUE THREAD

**Issue by RCasatta** [nabijaczleweli/cargo-update#200]
I would like to update dependencies to a version that is at least X days old as a measure to avoid flagrantly hijacked projects.

**Comment by nabijaczleweli** [comment]
Dependencies?

**Comment by RCasatta** [comment]
Yes,

Example:
my project has in Cargo.toml

```
[dependencies]
coollib=0.1
```
And a Cargo.lock with the same version.

coollib 0.2 is released 30 days ago.
coollib 0.3 is released yesterday.

I would like to use something like:

`cargo update --older 10d`

And the Cargo.lock will update to coollib 0.2 because 0.3 is too recent

**Comment by nabijaczleweli** [comment]
[bruh](https://github.com/rust-lang/cargo/issues/new?assignees=&labels=C-feature-request&template=feature_request.yml)

**Comment by RCasatta** [comment]
Thanks and sorry for wrong posting
