### ISSUE TITLE
cargo-update compile failure results in bad executable state

### ISSUE THREAD

**Issue by starkat99** [nabijaczleweli/cargo-update#21]
Running `cargo install-update cargo-update` that results in a compile failure (e.g. because rc.exe wasn't in the path) leaves the `.cargo/bin` executables in a bad state. I ended up with at bad `cargo-install-update.exe` file that was 0 bytes (and not a symlink) and a `cargo-install-update.exe-0.6.2` file that was the previous version. The original executable was not restored and I had to manually restore it in order to run the update again (with the proper path).

**Comment by nabijaczleweli** [comment]
Definitely should not be the case, I'll investigate tomorrow

**Comment by nabijaczleweli** [comment]
Released in [`v0.6.5`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v0.6.5)
