### ISSUE TITLE
Update binaries with features

### ISSUE THREAD

**Issue by simonsan** [nabijaczleweli/cargo-update#211]
I have a few binaries (e.g. [arti (Tor)](https://crates.io/crates/arti) that need to be built with features enabled. In case of arti it's static building SQLite with a feature flag.

Not sure if this is an upstream issue, as I don't think `cargo install` is saving the features somewhere that were used when installing?

`cargo-update` could circumvent that if I could map it by myself in a, e.g. `toml` file that is used for lookup when running `cargo install-update`.

**Comment by ModProg** [comment]
maybe it would make sense to mention this in just one line in the readme? I also didn't know this and found it via issues.

Though I admit, I had only needed to look at the documentation.

**Comment by nabijaczleweli** [comment]
Sure: 70ac01494200e2cb295cbe0e2ab1bbd068c73d48
