### ISSUE TITLE
Feature request: Add an option to opt-out from using cargo binstall

### ISSUE THREAD

**Issue by spitfire05** [nabijaczleweli/cargo-update#218]
`cargo binstall` can be sometimes problematic (#213), so it'd be nice to force `cargo install-update` to using `cargo install`, even if `cargo-binstall` is in `PATH`.

Something along the lines of `--no-binstall` argument flag would be nice.

Thoughts?

**Comment by nabijaczleweli** [comment]
[Per manual](https://github.com/nabijaczleweli/cargo-update/blob/master/man/cargo-install-update.md#description):

If you want to do that globally, then don't have cargo-binstall in the PATH, I consider this a configuration item.

If you want to do this per-run, then do something like `-r "$(command -v cargo)"`.

If you want to do this per-crate, as I assume you do in this case, then configure something, like as `cargo install-update-config -v '>=0.0.0' the-crate`.

**Comment by spitfire05** [comment]
Ok, sounds reasonable. I guess this issue can be closed then.
