### ISSUE TITLE
Can't update binaries that require additional features

### ISSUE THREAD

**Issue by ahlinc** [nabijaczleweli/cargo-update#233]
_Hi! Thank you for the awesome tool that saves a lot of time!_

Recently I saw a situation that the `cargo install-update --all` command  wasn't able to update binaries that require that some features to be enabled.

<details>

![Screenshot from 2023-04-24 22-44-04](https://user-images.githubusercontent.com/14666676/234100041-8555041a-2cb9-4b86-8d29-367ab5088b6b.png)
</details>

It would be good if the tool would understand that a binary already is installed so it make sense to enable [`required-features`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field) by default.

**Comment by nabijaczleweli** [comment]
[Manual says](https://github.com/nabijaczleweli/cargo-update/blob/master/man/cargo-install-update-config.md): `cargo install-update-config -f cli tree-sitter-graph`

**Comment by ahlinc** [comment]
@nabijaczleweli thank you for pointing to the man.
But is it possible to happen automatically for **base** features that are mentioned in [required-features](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field)? The `cargo install-update-config` command can be used to enable additional features for a binary to enable, e.g., some additional functionality, but the _base required features_ are **the base** and may be handled automatically.

**Comment by ahlinc** [comment]
Thank you for explaining, I see that there is no the `required-features` in the index.
