### ISSUE TITLE
Failed to update index repository crates-io: [60] SSL peer certificate or SSH remote key was not OK (Peer's Certificate issuer is not recognized.).

### ISSUE THREAD

**Issue by woshilapin** [nabijaczleweli/cargo-update#234]
Whenever I try to run a command to update a package (or all packages), I end up with the following error.

```
❯ cargo install-update bat
    Polling registry 'https://index.crates.io/'
Failed to update index repository crates-io: package bat: HTTP 0.
❯ cargo install-update --list
    Polling registry 'https://index.crates.io/'
Failed to update index repository crates-io: package alacritty: HTTP 0.
```

I'm not sure what causes this. I was able to work with `cargo-update` for months (possibly years) without any problem. A possible cause would be my update to the latest Ubuntu 23.04 (the current error is one of the first things I did since I updated my Ubuntu). 

I did reinstall entirely `cargo-update` with `cargo install cargo-update`, but same result.

**Comment by nabijaczleweli** [comment]
What if you run `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=git cargo install-update -l`? Do you have any non-default config in `~/.cargo`?

**Comment by nabijaczleweli** [comment]
Can you try the current `master` branch (at least 743d5ab48e2f79932f44f3e0c9f2cc1747b51952)? It should write a useful message for this error and thus should help debug what the error actually si.

**Comment by nabijaczleweli** [comment]
Yep, that was also what I was gonna do :v (not that I can do much more)

I'll just upload a new release with the improved error reporting and make the issue subject reflective of the new error

**Comment by woshilapin** [comment]
> Let's wait for the dust to settle
The dust as settled, there seems to have been not much activity on this issue since. I'm closing it. Feel free to reopen if you feel that it should stay open.
