### ISSUE TITLE
Configuration: support setting environment variables for specific crates

### ISSUE THREAD

**Issue by alpha-tango-kilo** [nabijaczleweli/cargo-update#244]
I would like to be able to set an environment variable for the underlying `cargo install` call that happens when updating a specific crate

Use case: when updating `sccache` on Windows, you can't have `sccache` running, because you can't replace the running executable with the new one. Thus, one of the easiest ways to work around this is to set `RUSTC_WRAPPER` to be blank to stop the compilation from using (and therefore running) `sccache`, allowing the update to complete successfully

Is this a reasonable feature idea, and would you be open potentially to a PR for this functionality? (No idea when I may get time to do this, but it seems like it should be pretty doable)

Alternatively one could instead hard-code this edge case for just this one crate on just Windows, if that would be preferred over adding a new feature

**Comment by nabijaczleweli** [comment]
I'm worried "environment: [string | null]" will inevitably become "parse environment substitutions as well", which would be really annoying. But lets just say it won't, and we're in business tbh.

**Comment by alpha-tango-kilo** [comment]
Works perfectly, thanks so much! The only thing I'd suggest is maybe some shorter aliases, e.g. `--{,clear-,inherit-}env`, but regradless the current implementation serves my purpose flawlessly 😄

**Comment by nabijaczleweli** [comment]
There's `-e` and `-E` for set/clear, inherit is effectively a partial `-r` so it can stay long and there's no obvious short letter. It's already annoying that it's `--...-environment` instead of `--...-environment-variable` but that'd be insane imo

Released in [`v13.2.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v13.2.0)
