### ISSUE TITLE
Is there a way to specify the number of threads to use?

### ISSUE THREAD

**Issue by JSorngard** [nabijaczleweli/cargo-update#246]
My laptop is very old, and if I run `cargo-update` it will use all cores, which leaves my laptop difficult to use until it finishes updating. With the normal `cargo install` command I can specify the number of threads to leave some headroom for other processes, but `cargo-update` has no such option as far as I can see. Am I missing something obvious, or could something like that be added?

**Comment by nabijaczleweli** [comment]
`cargo install` takes `-j`, trivial to forward that – can you try the current `master` branch (at least 38c18d91e3fdd7a7cbc4b52b0bd86933845029dd)?

**Comment by nabijaczleweli** [comment]
aaand in github's continued war against its users i can't tag this [enhancement]

**Comment by JSorngard** [comment]
That definitely seems to work :D

**Comment by nabijaczleweli** [comment]
Great; release in [`v13.3.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v13.3.0).
