### ISSUE TITLE
Keep the features

### ISSUE THREAD

**Issue by ncihnegn** [nabijaczleweli/cargo-update#249]
I installed ripgrep with `--all-features` but it seems `cargo install-update -a`  will update it with no features.

**Comment by nabijaczleweli** [comment]
Per [manual](https://github.com/nabijaczleweli/cargo-update/blob/master/man/cargo-install-update-config.md#options): run `cargo install-update-config -f feat1 -f feat2 ripgrep`

**Comment by ncihnegn** [comment]
That defeats the purpose of `install-update -a`.

**Comment by NobodyXu** [comment]
> That defeats the purpose of `install-update -a`.

You just need to configure it once and then it will be saved as configuration and applied during install-update
