### ISSUE TITLE
Internal matching of custom registry and source for sparse indices fails

### ISSUE THREAD

**Issue by nevsal** [nabijaczleweli/cargo-update#253]
The command `cargo install-update` doesn't display or handle crates installed from sparsed-index source/registry (apart from crates.io which is handled differently throughout its source code). It therefore also re-installs for `cargo install-update -i xyz` even if crate *xyz* has already been installed.

This affects configurations (~/.cargo/config.toml) akin to

```
[registry]
default = "local-crates-io"

[source.crates-io]
replace-with = "local-crates-io"
 
[registries.local-crates-io]
index = "sparse+https://localserver/directory/crates.io/index/"
 
[source.local-crates-io]
registry = "sparse+https://localserver/directory/crates.io/index/"
```

which has become a current default for [Jfrog Artifactory](https://jfrog.com/help/r/jfrog-artifactory-documentation/cargo-package-registry) package registries.

The relevant code has been identified and a pull request will follow shortly.

**Comment by nabijaczleweli** [comment]
Fix released in [`v13.4.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v13.4.0)
