### ISSUE TITLE
Unable to list/update packages after installing package using cargo binstall --git

### ISSUE THREAD

**Issue by fnuttens** [nabijaczleweli/cargo-update#261]
After installing [markdown-oxide](https://github.com/Feel-ix-343/markdown-oxide) this way:

```shell
cargo binstall --git 'https://github.com/feel-ix-343/markdown-oxide' markdown-oxide
```

I get the following error:

```shell
$ cargo install-update -l
    Polling registry 'https://index.crates.io/'.................
Failed to update index repository crates-io: package markdown-oxide doesn't exist: HTTP 404.
```

What am I missing?

**Comment by nabijaczleweli** [comment]
What does `~/.cargo/.crates.toml` say?

**Comment by fnuttens** [comment]
@nabijaczleweli I didn’t realize there were hidden files here ^^'

```toml
[v1]
# …
"markdown-oxide 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["markdown-oxide"]
```

I guess I have to change this to `(git+https://github.com/feel-ix-343/markdown-oxide)` or something?

**Comment by nabijaczleweli** [comment]
In your particular case: yes, unfortunately

But in the general case: @NobodyXu needs to fix cargo-binstall to write the correct metadata to `.crates.toml`

**Comment by NobodyXu** [comment]
Thanks, I've opened an issue in cargo-binstall, would fix it soon.

**Comment by nabijaczleweli** [comment]
Closing as external (https://github.com/cargo-bins/cargo-binstall/issues/1815)
