### ISSUE TITLE
Prompt user before performing updates

### ISSUE THREAD

**Issue by Squidroot2** [nabijaczleweli/cargo-update#263]
This is just a suggestion for an enhancement.

I typically run cargo-update within a command that updates everything on my system like this:
```sh
sudo dnf update --refresh
flatpak update
cargo install-update --all
```

`dnf` and `flatpak` prompt me with the updates it is about to make before doing it but cargo-update does not. It would be nice if cargo-update worked the same way: after showing the updates it is going to make, prompt the user for a y/n

To not make a breaking change, the default behavior could stay the same but a "--confirm" option is added.

**Comment by nabijaczleweli** [comment]
`cargo install-update -la; printf 'Update the above? '; read -r resp && [ "${resp#[yY]}" != "$resp" ] && cargo install-update -a`
