### ISSUE TITLE
FR: An option to disable some of `cargo binstall`'s strategies

### ISSUE THREAD

**Issue by ilyagr** [nabijaczleweli/cargo-update#264]
I've had some occasional problems with Quickinstall (https://github.com/cargo-bins/cargo-quickinstall/issues/250, https://github.com/cargo-bins/cargo-quickinstall/issues/255). I'd like there to be an option to pass `--disable-strategies quick-install` to `cargo binstall` when called from `cargo install-update`.

A workaround is to set the option with an environment variable:

    BINSTALL_STRATEGIES=cargo-meta-data,compile cargo install-update

I haven't tested it yet, but I believe it should work.

**Comment by nabijaczleweli** [comment]
If only `cargo-meta-data` and `compile` work for you then you should specify that exactly as you noted, yeah. Not sure what more cargo-install could do here.
