### ISSUE TITLE
New version detection not working properly.

### ISSUE THREAD

**Issue by dougg0k** [nabijaczleweli/cargo-update#271]
Hi,

I have been using the crate with the command `cargo install-update -a` to check and update all packages from tools that I use.

I noticed a new version was released for nushell, but it is not being detected.

```
nu ❯ cargo install-update -a
    Polling registry 'https://index.crates.io/'......................................

Package          Installed             Latest                               Needs update
nu               v0.96.1               =0.96.1                              No
```

https://crates.io/crates/nu

It worked before, but not now, unsure why. Is there a cache that could be causing this?

---

I also noticed that it didnt for this crate.

```
cargo-update     v14.0.0               =14.0.0                              No
```

Latest version seems to be `14.0.2`

**Comment by nabijaczleweli** [comment]
Yeah, 14.0.0 parses Cargo's `.crates2.json` in such a way that it treats "the latest version updated to" as "never update past this version" (`Latest` having a `=` is a symptom of this).

This should go away if you do `cargo install -f cargo-update` hopefully?

**Comment by dougg0k** [comment]
It did. Thanks.
