### ISSUE TITLE
Can't install via binstall

### ISSUE THREAD

**Issue by MANICX100** [nabijaczleweli/cargo-update#272]
cargo binstall cargo-update
 INFO resolve: Resolving package: 'cargo-update'
 WARN Failed to send quickinstall report for package cargo-update-14.0.2-x86_64-unknown-linux-gnu: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-update-14.0.2-x86_64-unknown-linux-gnu.tar.gz: HTTP status client error (402 Payment Required) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-update-14.0.2-x86_64-unknown-linux-gnu.tar.gz)
 WARN Failed to send quickinstall report for package cargo-update-14.0.2-x86_64-unknown-linux-musl: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-update-14.0.2-x86_64-unknown-linux-musl.tar.gz: HTTP status client error (402 Payment Required) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/cargo-update-14.0.2-x86_64-unknown-linux-musl.tar.gz)
 WARN The package cargo-update v14.0.2 will be installed from source (with cargo)

**Comment by nabijaczleweli** [comment]
Don't strictly see how that's ad rem for this tracker. Maybe report this to cargo-binstall if you think think your subscription isn't being honoured? or something

**Comment by NobodyXu** [comment]
The warning you've seen is from quickinstall telemetry, it doesn't affect the actual package resolution.

**Comment by MANICX100** [comment]
I believed that cargo binstall just queried sources from the developer so some subscription needed renewal. It appears I was wrong.
