### ISSUE TITLE
Support for cargo `install-update -a --locked`

### ISSUE THREAD

**Issue by luccahuguet** [nabijaczleweli/cargo-update#273]
I am aware of https://github.com/nabijaczleweli/cargo-update/issues/152 and https://github.com/nabijaczleweli/cargo-update/issues/191

but i think it would be much more user friendly allowing for direct usage of the `--locked` option

if implementing this is completely out of the table, we can close this issue, no problems.

**Comment by NobodyXu** [comment]
P.S. cargo-binstall does support `--locked`, so there shouldn't be any issue from cargo-binstall

**Comment by luccahuguet** [comment]
> P.S. cargo-binstall does support `--locked`, so there shouldn't be any issue from cargo-binstall

thank you Jiahao

I'll consider using binstall directly then

**Comment by luccahuguet** [comment]
this why im using cargo-update btw 

https://github.com/luccahuguet/rustifier

**Comment by nabijaczleweli** [comment]
Given that you're bypassing actual cargo-update configuration and you just want to add Some String to cargo argv, the manual prescribes `CARGO_INSTALL_OPTS=--locked` for this.

**Comment by nabijaczleweli** [comment]
Admittedly, this disables the cargo-binstall upcall, but then so does any config. But clearly this is something users keep wanting for.. some reason.

**Comment by nabijaczleweli** [comment]
Can you try the current `master` branch (at least addb658d22ef60c9edc22bb8a3dc9531f0df048c)?

**Comment by luccahuguet** [comment]
> Admittedly, this disables the cargo-binstall upcall, but then so does any config. But clearly this is something users keep wanting for.. some reason.

Its stronger than me

I admit it, it’s not rational

**Comment by luccahuguet** [comment]
> Can you try the current `master` branch (at least addb658d22ef60c9edc22bb8a3dc9531f0df048c)?

This looks beautiful https://github.com/nabijaczleweli/cargo-update/commit/addb658d22ef60c9edc22bb8a3dc9531f0df048c

You can check it with gitui (it breaks without --locked)

I will personally wait for the new release tho...

Thank you for listening to your users!

**Comment by nabijaczleweli** [comment]
Released in [`v14.1.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v14.1.0)
