### ISSUE TITLE
[ bug ] Reports on packages that no longer exist

### ISSUE THREAD

**Issue by yonas** [nabijaczleweli/cargo-update#275]
After removing some programs from `~/.cargo/bin`, they still appear in `cargo install-update -a`.

argo-install-update 14.1.1
OS: Ubuntu 24

**Comment by nabijaczleweli** [comment]
You removed Some File, this doesn't uninstall the package. Uninstall the package if you don't want to see updates for it.

**Comment by yonas** [comment]
@nabijaczleweli What package? I installed them via `cargo install`?

**Comment by nabijaczleweli** [comment]
Then you will be delighted to know that you can do `cargo uninstall` to undo this.

**Comment by yonas** [comment]
Thanks!
