### ISSUE TITLE
cargo update not showing some new crate updates, and for quite a while

### ISSUE THREAD

**Issue by luccahuguet** [nabijaczleweli/cargo-update#281]
yazi-fm v0.4.0 is already in development and the current latest version is 0.3.3

I occasionally run `cargo install-update --all` or  `cargo install-update --list` and I always trust the output

However today I noticed that yazi-fm was in version 0.2.5 still, and checking yazi's docs, I see the latest on crates.io is actually 0.3.3

well, how come is that? I think. 

it seems to be a bug on this project's side. Or something I, as a user, did wrong. 

running `cargo install yazi-fm` fixed my problem: "Replaced package `yazi-fm v0.2.5` with `yazi-fm v0.3.3` (executable `yazi`)"

but what I want is to be able to trust that this project will keep my cargo programs updated..

**Comment by nabijaczleweli** [comment]
You're probably seeing a bug in cargo-update [v14.0.0](https://github.com/nabijaczleweli/cargo-update/releases/tag/v14.0.0) that, under some circumstances, made some packages not update. Sometimes this "some package" is cargo-update. Unfortunately there's no way to fix this except issuing `cargo install -f cargo-update` manually.

**Comment by luccahuguet** [comment]
> You're probably seeing a bug in cargo-update [v14.0.0](https://github.com/nabijaczleweli/cargo-update/releases/tag/v14.0.0) that, under some circumstances, made some packages not update. Sometimes this "some package" is cargo-update. Unfortunately there's no way to fix this except issuing `cargo install -f cargo-update` manually.

Oh, that's a bad recursion problem. Thanks for the info

the culprit just got updated
`    Replaced package `cargo-update v14.0.0` with `cargo-update v15.0.0` (executables `cargo-install-update`, `cargo-install-update-config`)`

for others with the same problem, there is a shell alternative `cargo install $(cargo install --list | egrep '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')`

and a nushell one: 
```
def upcargo [] {
 cargo install --list
    | parse "{package} v{version}:"
    | get package
    | each {|p| cargo install $p}   
}
```

**Comment by luccahuguet** [comment]
lots of packages were not getting updated in `v14.0.0`

**Comment by nabijaczleweli** [comment]
If you update `cargo-update` past 14.0.0 then `cargo install-update -a` will update all the ones that weren't getting updated (it's possible that some stray configuration survives in `~/.cargo/.install_config.toml` and poisons later versions, but this is unlikely on average I think).
