### ISSUE TITLE
Shared object "libcurl.so.4" not found

### ISSUE THREAD

**Issue by pfr-dev** [nabijaczleweli/cargo-update#284]
NetBSD 10.0_STABLE
rust-1.79.0
cargo 1.79.0

```
~ λ cargo install-update -a 
/home/dave/.cargo/bin/cargo-install-update: Shared object "libcurl.so.4" not found
```

**Comment by nabijaczleweli** [comment]
Rebuild against your current libcurl (`cargo install -f cargo-update`) or install libcurl if you removed it (but isn't libcurl in base? so unlikely).

**Comment by pfr-dev** [comment]
Hmmmm no `libcurl` it seams... There is a `libcurl-gnutls` in the repostiries but installing this doesn't seem to help.

I also tried `cargo install -f cargo-update` but same result :(

**Comment by nabijaczleweli** [comment]
Oh this a new installation and it still don't work? so it's linking to ... some libcurl. and then not finding it.

How's about `cargo install -f --features vendored-libcurl cargo-update`?

**Comment by pfr-dev** [comment]
Thank you, this worked 👍
