### ISSUE TITLE
Reverse the crates list

### ISSUE THREAD

**Issue by azzamsa** [nabijaczleweli/cargo-update#285]
Hi, 👋🏽 

I install most of my apps using `cargo`. So it is a huge list. Running `cargo install-update -a` yields a long list and I need to scroll to see what's being updated because it is on the top of the list. 

Can we have something like `cargo install-update --all --list-reverse` to have the list reversed so I don't have to scroll everytime I run an update?

If you are okay with this, give me a clue and I will make a PR.

Thanks for `cargo-update` I use it almost every day! 🍩

**Comment by nabijaczleweli** [comment]
The historical precedent for filters like this is something like "use `| grep -v No$`" (which would remove all the crates that don't need updates from the listing). Is this an acceptable substitution for your use-case?

**Comment by azzamsa** [comment]
```
🦄 cargo install-update --all | grep -v No
    Polling registry 'https://index.crates.io/'.............................................................

Package             Installed  Latest                               Needs update
cargo-nextest       v0.9.85    v0.9.86                              Yes
typos-cli           v1.28.2    v1.28.3                              Yes

Updating cargo-nextest
```

OMG, I think I need to learn some coreutils properly 😢 
Thanks a lot for `cargo-update`  🍔
