### ISSUE TITLE
Can this update itself?

### ISSUE THREAD

**Issue by saghm** [nabijaczleweli/cargo-update#3]
Is `cargo-update` capable of updating itself? (Sorry, not so much an issue as a technical question, but I wasn't sure where else to ask it)

**Comment by nabijaczleweli** [comment]
It will try, for it does not discriminate, and will fail on Windooze (obviously), but might work on Linux (IIRC you can replace an exec while it's running there)

**Comment by saghm** [comment]
Interesting. I'm on Linux, so the next time you update the crate, I'll let you know what happens!

**Comment by nabijaczleweli** [comment]
What you can do to easily test is edit `$HOME/.cargo/.crates.toml` and change the version there. Since that's all we parse, it'll go ahead and try to update.

**Comment by nabijaczleweli** [comment]
Confirmed, works on Linux.
