### ISSUE TITLE
Add Cargo.lock to repository

### ISSUE THREAD

**Issue by ishitatsuyuki** [nabijaczleweli/cargo-update#30]
Cargo.lock is normally included for projects with a binary. By the way, it's ignored when building as library dependency.

**Comment by nabijaczleweli** [comment]
Dupe of #10

**Comment by ishitatsuyuki** [comment]
May I continue the discussion here? All projects contains more than one binary, independent of the usecase, **should** have a lockfile. 

http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by nabijaczleweli** [comment]
No, you mayn't. The executable is a usage example. EOT
