### ISSUE TITLE
Incompatible with upcoming bare Cargo registry

### ISSUE THREAD

**Issue by ishitatsuyuki** [nabijaczleweli/cargo-update#32]
rust-lang/cargo#4026 introduced local registry without checkout, and this tool doesn't work since it relies on registry directory structure.

The old format isn't compatible with the new format at all, so choose one:
- port and branch the code
- use the system Cargo executable to query them
- link to Cargo (bad buildtime)
- directly query crates.io (used by cargo-edit)

**Comment by nabijaczleweli** [comment]
Hmmm, I guess we could basically do the same thing as we do now but through the `git2` layer rather than raw FS.

4026 landed in nightly 5 days ago, so it'll land in stable like 4 weeks from that, or does `cargo` release on a different cycle than `rustc`?

**Comment by ishitatsuyuki** [comment]
It should land as 0.20.0, so 1 or 2 months. I think keeping the code in master until it hits stable is a good idea.

**Comment by nabijaczleweli** [comment]
Eh, the difference between non-bare and bare is only the location of the repo itself (and IIRC `git2` is smart enough to follow `.git`), so one can implement `git2`-based searching w/o breaking the current `cargo`.

**Comment by pravic** [comment]
>  nabijaczleweli closed this in 1ec0f2f 32 minutes ago

Doesn't work though:

```
cargo install-update -al
    Updating registry `https://github.com/rust-lang/crates.io-index`

Failed read master branch of registry repositry at
 $CARGO_HOME/registry/index/github.com-1ecc6299db9ec823.
```

**Comment by nabijaczleweli** [comment]
Can you check that that directory is actually a git repository? It works for my setup, but

**Comment by pravic** [comment]
> ls $CARGO_HOME/registry/index/github.com-1ecc6299db9ec823
> config  description  FETCH_HEAD  HEAD  hooks  info  objects  refs

**Comment by nabijaczleweli** [comment]
Interesting, a manually-cloned bare repo works for me. Try replacing `master` with `HEAD` at main.rs#L57, *maybe*? Otherwise printing that error would work as well 🤔

**Comment by pravic** [comment]
> error: Error { code: -3, klass: 4, message: "Revspec \'HEAD\' not found." }.

**Comment by nabijaczleweli** [comment]
And it's the same with `master`, I presume?

**Comment by pravic** [comment]
Yep

**Comment by nabijaczleweli** [comment]
That's definitely *interesting*, but I can't see how I can do anything else than read `master` or `HEAD` (but probably `master)?

**Comment by pravic** [comment]
https://libgit2.github.com/libgit2/#HEAD/group/revparse
https://git-scm.com/docs/git-rev-parse.html#_specifying_revisions

You have to use an `origin/master`, I guess. Because it isn't a working copy and we have no master branch in it.
Works for me.

**Comment by nabijaczleweli** [comment]
If that's the last thing then I'm gonna release it, if y'all have no objections?

**Comment by pravic** [comment]
I don't know. It seems, it works on nightly, so I have no objections.
Have you checked on stable Rust?

**Comment by nabijaczleweli** [comment]
I only use stable so yes.

**Comment by nabijaczleweli** [comment]
Released in [`v1.0.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.0.0)

**Comment by durka** [comment]
I'm seeing this issue in v1.3.1.

```
durska:piston-image alex$ rustc -vV
rustc 1.22.0-beta.3 (cc6ed0640 2017-11-13)
binary: rustc
commit-hash: cc6ed0640fbcd2dff95b4532fd12aa0d6c545f28
commit-date: 2017-11-13
host: x86_64-apple-darwin
release: 1.22.0-beta.3
LLVM version: 4.0
durska:piston-image alex$ cargo -vV
cargo 0.23.0-beta (cee38cd30 2017-11-12)
release: 0.23.0
commit-hash: cee38cd30d16b343b13721ec813dc89eb1c1642d
commit-date: 2017-11-12
durska:piston-image alex$ cargo install-update -V
cargo-install-update 1.3.1
durska:piston-image alex$ cargo install-update -al
    Updating registry `https://github.com/rust-lang/crates.io-index`

Failed read master branch of registry repositry at /Users/alex/.cargo/registry/index/github.com-88ac128001ac3a9a.
```

**Comment by durka** [comment]
The `refs/heads` directory is empty. This could be a problem.

**Comment by durka** [comment]
The problem seems to be that it's reading the wrong index. `github.com-88ac128001ac3a9a` has a later modified date on the directory, but `github.com-1ecc6299db9ec823` has newer files in it.
