### ISSUE TITLE
Unable to list updates of installed packages

### ISSUE THREAD

**Issue by pravic** [nabijaczleweli/cargo-update#33]
```
$ cargo install-update --list
error: The following required arguments were not provided:
    <PACKAGE>...

USAGE:
    cargo install-update <PACKAGE>... --list

For more information try --help
```

**Comment by nabijaczleweli** [comment]
[Example number three](https://cdn.rawgit.com/nabijaczleweli/cargo-update/man/cargo-install-update.1.html#EXAMPLES), also you could've just read the `--help` page or the manual but who has time for that right

**Comment by pravic** [comment]
--help isn't so clear for that case. 
Well, nevermind, #32 is fatal issue anyway.

**Comment by nabijaczleweli** [comment]
Which #32, the one that's closed and fixed or what

**Comment by pravic** [comment]
Yeah, it was closed at the same time.
