### ISSUE TITLE
Allow specifying a version of a package to install.

### ISSUE THREAD

**Issue by tomprince** [nabijaczleweli/cargo-update#37]
I'd like to be able to specify a version to install when using `cargo install-update -i`. I'd like to be able to use this in travis to install a pinned version of packages like rustfmt/clippy without needing to manually check if the package is installed or the correct version.

**Comment by nabijaczleweli** [comment]
That sounds like a job for `cargo install --force --vers XXX YYY`, unless I'm missing some obvious advantage basically rewriting the UI and update-check layers would bring?

**Comment by tomprince** [comment]
I'd like to avoid reinstalling the package if it is already installed and of the correct version. The use-case I have is installing clippy in travis builds. For example, I'd like to replace the code [here](https://github.com/brson/cargobomb/blob/a85b4b07a7ca94316e286b00cd10abf4b736cc3e/.travis.yml#L19-L21) with something like `cargo install-update -i clippy:$CLIPPY_VERSION`.

**Comment by nabijaczleweli** [comment]
ya alright

**Comment by nabijaczleweli** [comment]
Currently waiting on https://github.com/danielpclark/array_tool/pull/12

**Comment by nabijaczleweli** [comment]
https://github.com/danielpclark/array_tool/pull/12 landed in `array_tool` `0.4.0`

**Comment by nabijaczleweli** [comment]
did that do the thing for you or is it still kinda off

**Comment by tomprince** [comment]
Yes, that appears to work.

**Comment by nabijaczleweli** [comment]
Released in [`v1.1.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.1.0).
