### ISSUE TITLE
Add --vers flag

### ISSUE THREAD

**Issue by vitiral** [nabijaczleweli/cargo-update#41]
`cargo install` has a `--vers` flag which lets you specify the version to install. Can that be added to this crate?

If it was added this crate would be absoltely perfect!

**Comment by vitiral** [comment]
the value of this is it would let me just call `cargo install-update PACKAGE --vers VERSION` in environment scripts and it would make sure my versions are the same as the repo's.

**Comment by nabijaczleweli** [comment]
If by `--vers` you mean #37, used like https://github.com/brson/cargobomb/pull/98, then this is a dupe :v

**Comment by vitiral** [comment]
Sorry, I didn't see it in the docs or open issues! Looks like this is already released
