### ISSUE TITLE
Unable to install on mac

### ISSUE THREAD

**Issue by dns2utf8** [nabijaczleweli/cargo-update#45]
Hi

I am currently working on mac, but I can not compile the openssl crate without messing up the system with homebrew...
Is there a way to switch to [native-tls](https://github.com/sfackler/rust-native-tls)?

**Comment by mati865** [comment]
Cargo-update doesn't depend on openssl.
You should report it for dependent crate that pulls openssl.

**Comment by mati865** [comment]
`cargo-update` depends on [git2-rs](https://github.com/alexcrichton/git2-rs) which in turn depends on [ssh2-rs](https://github.com/alexcrichton/ssh2-rs).
When next `ssh2-rs` is released this [should be fixed](https://github.com/alexcrichton/ssh2-rs/pull/71).

**Comment by nabijaczleweli** [comment]
Cool!

**Comment by mati865** [comment]
`ssh2-rs` 0.3.2 containing fix has been released back in the summer.
Probably fine to close.

**Comment by nabijaczleweli** [comment]
If you say so!
