### ISSUE TITLE
Opened pull request to promote cargo-update

### ISSUE THREAD

**Issue by pahhnv** [nabijaczleweli/cargo-update#46]
Hi,

I've opened a pull request [(#320)](https://github.com/rust-unofficial/awesome-rust/pull/320) at [awesome-rust](https://github.com/rust-unofficial/awesome-rust) (at the end of the build system section) to feature cargo-update as I've been using it for the last months and it's been incredibly handy. 

Is there a reason why this repo should not be featured? I can't see why not, I just want to make sure there's no problem with cargo-update I'm not aware of.

**Comment by nabijaczleweli** [comment]
There's this one external issue that affects seemingly random people but that's external and will (probably) auto-fix when `ssh2-rs` or `git2-rs` updates.

Also, thanks!
