### ISSUE TITLE
CARGO_HOME support

### ISSUE THREAD

**Issue by Yamakaky** [nabijaczleweli/cargo-update#5]

**Comment by nabijaczleweli** [comment]
So the lookup order would be `$CARGO_HOME` -> `$HOME/.cargo` -> fail?

**Comment by Yamakaky** [comment]
yes

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.1`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v0.3.1)

**Comment by Yamakaky** [comment]
Cool
