### ISSUE TITLE
Build fails for macOS 10.13

### ISSUE THREAD

**Issue by lewisinc** [nabijaczleweli/cargo-update#52]
Maybe I'm just not setting an environment variable that I should be - but building fails with `error: failed to run custom build command for 'libgit2-sys v0.6.15'`. I should probably file this with git2-rs, but I can't really verify that git2-rs breaks because I don't use it.

Also note that I have the Homebrew packages for openssl and libssh2 installed.

If this is a path configuration thing, it also might be nice to have that as part of the readme.

Attaching a log to be somewhat helpful
[log.txt](https://github.com/nabijaczleweli/cargo-update/files/1347206/log.txt)

Thanks

**Comment by nabijaczleweli** [comment]
Try setting `CMAKE_PREFIX_PATH` to where `libssh2` is installed (or up, or up from that, you get the gist)?

If that doesn't work, this is probably a problem with `git2-rs` (and you open an issue there should work, I think)?

**Comment by lewisinc** [comment]
No dice. I'll file an issue and see where it goes. Thanks

**Comment by nabijaczleweli** [comment]
Cool, I love build system errors :v

**Comment by lewisinc** [comment]
I've filed a an issue with `git2-rs` here for reference: https://github.com/alexcrichton/git2-rs/issues/257

**Comment by mati865** [comment]
`libgit2-sys` 0.6.16 containing fix has been released over month ago.
Probably fine to close.

**Comment by nabijaczleweli** [comment]
If you say so!
