### ISSUE TITLE
Sometimes it freezes

### ISSUE THREAD

**Issue by pravic** [nabijaczleweli/cargo-update#59]
`$ cargo install-update -al` spawns a `"cargo" search ""` which is runs forever.

> cargo 0.23.0 (61fa02415 2017-11-22)
> cargo-update v1.3.2
> win7 x64

Nightly cargo behaves the same. 

I have encountered such issue time ago with the same version, but was not sure about the reason (was it due to 1.3.2 or new cargo may be). Just tried to reinstall cargo-update which helped me.

However now it freezes again. But I have to say that on another pc `cargo search ""` does not freeze. So, the problem is that `cargo install-update` spawns the empty `cargo search`.

**Comment by nabijaczleweli** [comment]
Can you try replacing

```rust
let search_res = Command::new("cargo").arg("search").arg("").status().unwrap();
```

with

```rust
let search_res = Command::new("cargo").arg("search").status().unwrap();
```

or

```rust
let search_res = Command::new("cargo").arg("search").arg("\"\"").status().unwrap();
```

? There might be some funky interaxion going on between cargo and an empty arg, even though there should not (and doesn't on my machine; same config, but W10).

**Comment by pravic** [comment]
Well.. As I see, the empty `cargo search` was made by purpose. So, it looks like a cargo problem that it updates registry so long.

And there is no difference between `cargo search` and `cargo search ""`.

I did some tests. Sometimes it runs, like, forever. Sometimes it takes ~ 1 minute. And in rest cases it exits fast. Next time I'll run it with file/network trace and verbose logs.

**Comment by nabijaczleweli** [comment]
How'd that fare?

**Comment by nabijaczleweli** [comment]
Any updates on this?

**Comment by pravic** [comment]
It works flawless. Let's pretend that the problem has gone.

**Comment by nabijaczleweli** [comment]
"Pretend" :v
But oh well. if it works…
