### ISSUE TITLE
Please list dependencies in the readme

### ISSUE THREAD

**Issue by smurfendrek123** [nabijaczleweli/cargo-update#67]
While installing, i currently have to compile until i get an error message (failed to run custom build command for $missing package$). I can then restart the compilation after installing the missing package.

It would be nice if the dependencies were listed out somewhere.

On my fedora 27 machine I had to install: libgit2-devel
libssh2-devel
openssl-devel
cmake

If you'd like i can submit a pull request to add information relevant to fedora 27, but i don't know how to list all dependencies.

**Comment by nabijaczleweli** [comment]
Added more prominent sexion to README. Is it quite readable?

**Comment by smurfendrek123** [comment]
Thank you so much! You're doing great work, it really makes working with rust a lot easier!

**Comment by nabijaczleweli** [comment]
Released in [`v1.5.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.5.0).
