### ISSUE TITLE
Some idea? cargo-pkg

### ISSUE THREAD

**Issue by biluohc** [nabijaczleweli/cargo-update#69]
Your work is good，
but we maybe need a package manager?

```sh
cargo pkg install  [--type git/path] xxx 

cargo pkg remove xxx  

cargo pkg list [--type git/path] 

cargo pkg update [-a] [--git]

cargo pkg init (check .crates.toml and install all)
```

**Comment by nabijaczleweli** [comment]
You mean `cargo`?

**Comment by mati865** [comment]
See if `cargo-edit` is what you wanted.

**Comment by biluohc** [comment]
@mati865 
cargo-edit  can manage the dependencies for a project, but I need a tool to manage the installed-executables.

cargo could  `install` or  `install --list`(it is very simple) now ,
 If need to remove,  should to rm the file and modify the `$CARGO_HOME/.crates.toml`(delete the  installled log) .

Perhaps, I should to wait cargo compeltely.

**Comment by nabijaczleweli** [comment]
I did what I could with the formatting and spelling but I still haven't the faintest as to what you're talking about. Have you seen `cargo uninstall`?

**Comment by biluohc** [comment]
@nabijaczleweli 
Thanks you , I need `cargo uninstall`.
