### ISSUE TITLE
Stopped working with a recent nightly

### ISSUE THREAD

**Issue by svenstaro** [nabijaczleweli/cargo-update#72]
Since a recent version of rust/cargo through rustup I get this:

    cargo install-update -a
    error: The subcommand 'install-update' wasn't recognized

I tried reinstalling cargo-update and it's definitely listed in `cargo list`. What's up here?

**Comment by mati865** [comment]
Now that's a new record of duplicates, original issue: #68.

**Comment by svenstaro** [comment]
Ah I see. Alright.
