### ISSUE TITLE
subcommand wasn't recognized

### ISSUE THREAD

**Issue by zethra** [nabijaczleweli/cargo-update#73]
When I run `cargo install-update -a` I get:
```
error: The subcommand 'install-update' wasn't recognized
        Did you mean 'install'?
If you believe you received this message in error, try re-running with 'cargo -- install-update'
USAGE:
    cargo [OPTIONS] [SUBCOMMAND]
For more information try --help
```

**Comment by nabijaczleweli** [comment]
While I intellectually understand why one'd report the *fourth* duplicate of #68 I will never really understand the necessity for such axion.

**Comment by zethra** [comment]
Well if you left #68 open until the issue was fixed (even if not a bug in cargo-update itself) people would see it and stop opening new issues (at least I wouldn't have).

**Comment by nabijaczleweli** [comment]
Well if people did their due diligence and went through closed issues they'd see the previous four issues on the topic :v oh well

**Comment by kbknapp** [comment]
This has finally made it into the latest nightly `cargo` build too - so the fix is `rustup update nightly`

**Comment by nabijaczleweli** [comment]
Thank @kbknapp, eternal praise be unto him.
