### ISSUE TITLE
Check for broken packages

### ISSUE THREAD

**Issue by RazrFalcon** [nabijaczleweli/cargo-update#81]
I often see something like 

```
/home/razr/.cargo/bin/cargo-tree: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory
```

Reinstalling fixes the problem. Can `cargo-update` check for such broken packages too and reinstall them?

**Comment by nabijaczleweli** [comment]
Don't you need to *run* them to check for that? If so, I sure as hell ain't running (potentially) 50 execs w/ no args 🤔

**Comment by matthiaskrgr** [comment]
@RazrFalcon https://github.com/matthiaskrgr/cargo-rebuild-check should have you covered I believe

**Comment by nabijaczleweli** [comment]
Closing for the time being, following @matthiaskrgr's great crate and the reporter seeming to have found it.
