### ISSUE TITLE
Rebuild all packages with specific toolchain

### ISSUE THREAD

**Issue by ultinous-attila** [nabijaczleweli/cargo-update#83]
Some packages require nightly version of rust, and when I rustup update, all the nightly builds are broken. It would be nice if a `cargo install-update -f --toolchain nightly` or something similar could rebuild all and only necessary packages.

**Comment by nabijaczleweli** [comment]
Could you check current `master` with "-s/--filter toolchain=nightly" and see if it works for you?

**Comment by ultinous-attila** [comment]
`cargo run --release --bin cargo-install-update -- install-update -la -s toolchain=nightly` works perfectly, thank you.
(commit `0979f778d8ea3d703307290c72b5e93913e2e688`)

**Comment by nabijaczleweli** [comment]
Released in [`v1.6.0`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.6.0).
