### ISSUE TITLE
Updating git binaries seems to be broken

### ISSUE THREAD

**Issue by jcgruenhage** [nabijaczleweli/cargo-update#85]
I was running `cargo install-update --all --git` twice in a row and noticed that it did the same thing twice, at least it said it was going to. It compiled things, but it doesn't seem to actually install it, as 

```
[jcgruenhage@localhost ~]$ cargo install-update -ag
    Updating registry `https://github.com/rust-lang/crates.io-index`

Package       Installed      Latest         Needs update
bat           v0.4.1         v0.4.1         No
cargo-edit    v0.3.0-beta.1  v0.3.0-beta.1  No
cargo-update  v1.5.2         v1.5.2         No
diceware      v0.1.0         v0.1.0         No
exa           v0.8.0         v0.8.0         No
tealdeer      v1.0.0         v1.0.0         No

No packages need updating.
Package    Installed                                 Latest                                    Needs update
alacritty  6cbae83f174fa6d114ea66b1f8dd6185950ca835  128c25ee8b31473a6514e9bcaa59d8f9e66ea3a7  Yes
topgrade   b3c8044ad35404222ecbbc3f741c542cbe3d049e  ca12f8e513463301cf765057c93fd8ebedab77af  Yes
```
keeps showing the same refs for installed and latest when running it again.

The problem might also be that detection of "Installed" is broken and not the installing.

**Comment by mati865** [comment]
Probably you are using stable or beta toolchain, duplicate of https://github.com/nabijaczleweli/cargo-update/issues/55

**Comment by jcgruenhage** [comment]
@mati865 Thank you, I must have overlooked that!
