### ISSUE TITLE
Could not compile `cargo-update`

### ISSUE THREAD

**Issue by sluongng** [nabijaczleweli/cargo-update#89]
![image](https://user-images.githubusercontent.com/26684313/43785826-63bbf7d2-9a91-11e8-9332-ef88a7e3a1aa.png)

Something wrong with this Git2 dependency? I am running on Ubuntu 18.04

**Comment by mati865** [comment]
Install `libgit2-dev` as said in `README.md`...

**Comment by sluongng** [comment]
Issue resolved
