### ISSUE TITLE
Use rawgit non-forever-cached URLs

### ISSUE THREAD

**Issue by pzmarzly** [nabijaczleweli/cargo-update#91]
In the repo there are links to rawgit, e.g. `https://cdn.rawgit.com/nabijaczleweli/cargo-update/doc/cargo_update/index.html` (added 2 years ago).

The problem is that according to [rawgit.com FAQ](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file), files linked by branch get cached permanently, so if you intend to change the content, you should instead link by tag or by commit ID:

> So, instead of a URL like https://cdn.rawgit.com/user/repo/branch/file, use a URL like https://cdn.rawgit.com/user/repo/tag/file or https://cdn.rawgit.com/user/repo/commit/file.

This would also make documentation updates atomic (there won't be a situation where CDN serves some files from new version and some from old).

**Comment by nabijaczleweli** [comment]
This is a good suggestion but I'm on the fence about the tradeoffs. I'll think about it, and thank you!

**Comment by nabijaczleweli** [comment]
Globally switched to githack, and IME the cache doesn't live too too long there. Thanks again for the suggestion, though
