### ISSUE TITLE
Can't install on Void Linux

### ISSUE THREAD

**Issue by VoidNoire** [nabijaczleweli/cargo-update#92]
After installing the prerequisites listed in the README and attempting to install cargo-update, I got [this output](https://ghostbin.com/paste/xra2a). Perhaps `pkg-config` also needs to be listed as a dependency in addition to those already listed in the README?

After installing `pkg-config` and enabling backtrace, I got [this output](https://ghostbin.com/paste/bwqdn). So is the issue with sfackler/rust-openssl? Is this related to #86? How should I go forward with this?

**Comment by mati865** [comment]
I don't know Void Linux but you'll probably need package `libressl-devel`.

**Comment by VoidNoire** [comment]
@mati865 Thanks for the suggestion. Unfortunately, it still fails after installing `libressl-devel`, with [the output](https://ghostbin.com/paste/e65x8). It seems I am missing Unix Makefiles, so I installed 'make' but even then, it still fails with [this output] (https://ghostbin.com/paste/44t8a).

**Comment by mati865** [comment]
@VoidNoire instructions in README are for the most popular Linux distribution (Ubuntu) where `cmake` pulls `make`, `*-dev` packages pull `pkf-config` and `libssl-dev` pulls right openssl package.

In your case you will need also `libgit2-devel` which would pull `libssh2-devel` and `libressl-devel` if they are absent.

There is variety of package managers and if @nabijaczleweli agrees there could be added another README section or wiki with distribution specific instructions.

**Comment by VoidNoire** [comment]
@mati865 I see. I think distro-specific instructions would be worthwile. If it's possible to do, it might be even better to add some logic in the installation process that automatically detects the distro in use and calls the distro's package manager to install the required packages.

I installed `libgit2-devel` and tried the installation again, but unfortunately it still fails, this time with [this output](https://ghostbin.com/paste/eaznc).

**Comment by nabijaczleweli** [comment]
Sexions for distros requiring special care sound great! (Though I am severely out of my depth here as I only use Windows and Debians :v)

**Comment by VoidNoire** [comment]
I installed it from the master branch by using:

`cargo install --git https://github.com/nabijaczleweli/cargo-update.git cargo-update`

and it sucessfully got built. It seems to work fine too as it's currently updating `ion-shell`. Thanks @mati865 and @nabijaczleweli. 😃

**Comment by nabijaczleweli** [comment]
Released in [v1.6.2](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.6.2).
