### ISSUE TITLE
Updating nightly packages

### ISSUE THREAD

**Issue by tforgione** [nabijaczleweli/cargo-update#95]
First, thank you for this very useful project !

So, I'm not sure if this is a real issue or an isolated problem, but here is the thing.

I installed [racer](https://github.com/racer-rust/racer) by doing `cargo +nighlty install racer` (because since 2.1, racer needs nightly), and when I run `cargo install-update`, I get errors like these:

``` 
error[E0554]: #![feature] may not be used on the stable release channel
```

which makes me guess `cargo-update` tries to build racer without the nightly option.

Am I correct ? Would there be a way to know if a package should be built with stable or nightly ?

**Comment by mati865** [comment]
You can use [`cargo install-update-config` to do it](https://cdn.rawgit.com/nabijaczleweli/cargo-update/man/cargo-install-update-config.1.html).
The command would be:
```
cargo install-update-config -t nightly racer
```

**Comment by tforgione** [comment]
Oh I see, thanks !

**Comment by nabijaczleweli** [comment]
Don't we have this in the manpage tho? :v

**Comment by mati865** [comment]
Yeah it's there but nobody seems to use `man` nowadays...

**Comment by tforgione** [comment]
I'm sorry :cry:

**Comment by nabijaczleweli** [comment]
It's quite alright (but do check the "documentation" and "manpage" links from README before opening an issue next time, if you'd be so kind).

**Comment by tforgione** [comment]
I'll make sure to do this next time. I apologize for the inconveniance.
